<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAXeayQM\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAXeayQM/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerAXeayQM.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerAXeayQM\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerAXeayQM\App_KernelProdContainer([
    'container.build_hash' => 'AXeayQM',
    'container.build_id' => '3763a0f5',
    'container.build_time' => 1588026302,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAXeayQM');
